### ISSUE TITLE
Failed to load the placeholder-text package

### ISSUE THREAD

**Issue by SJTreadway** [Nonameghost/atom-placeholder-text#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [placeholder-text](https://github.com/NoNameGhost/atom-placeholder-text) package, v0.1.1
### Stack Trace

Failed to load the placeholder-text package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/steventreadway/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:1:1)
    at /Users/steventreadway/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:8:3
    at Object.<anonymous> (/Users/steventreadway/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:8:3)
    at Object.<anonymous> (/Users/steventreadway/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/Users/steventreadway/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-ocean-dark-syntax-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
base16-ocean-dark-syntax-theme, v0.1.5
color-picker, v2.0.13
emmet, v2.3.14
file-icons, v1.6.11
minimap, v4.16.0
pigments, v0.18.1
placeholder-text, v0.1.1
project-manager, v2.6.5
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by pgrund** [comment]
Same on windows ... 


**Atom Version**: 1.2.4
**System**: Windows 7 Enterprise (SP1) 64 bit
**Thrown From**: [placeholder-text](https://github.com/NoNameGhost/atom-placeholder-text) package, v0.1.1


### Stack Trace

Failed to load the placeholder-text package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (C:\Users\grund\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:1:1)
    at C:\Users\grund\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:8:3
    at Object.<anonymous> (C:\Users\grund\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:8:3)
    at Object.<anonymous> (C:\Users\grund\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\grund\AppData\Local\atom\app-1.2.4\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "emmet-simplified"
    ],
    "excludeVcsIgnoredPaths": false,
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v1.1.0
build, v0.49.2
build-tools, v4.2.1
color-picker, v2.0.13
emmet, v2.3.15
json-schema, v0.1.15
keyboard-localization, v1.4.10
language-apache, v1.3.0
language-docker, v1.1.3
language-dot, v1.6.0
line-ending-converter, v1.3.2
linter, v1.11.2
linter-js-yaml, v1.2.4
linter-jsonlint, v1.0.1
linter-xmllint, v1.1.0
minimap, v4.16.2
pigments, v0.19.1
placeholder-text, v0.1.1
raml, v0.2.0
svn, v0.0.8
tree-view-git-branch, v0.0.6

# Dev
No dev packages
```

**Comment by Chrisedmo** [comment]
Any updates on this? Still getting the message.

**Comment by Chrisedmo** [comment]
Time to uninstall the plugin then.

**Comment by Disane87** [comment]
Same here
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: MSCHOT-MF4
**Thrown From**: [placeholder-text](https://github.com/NoNameGhost/atom-placeholder-text) package, v0.1.1


### Stack Trace

Failed to load the placeholder-text package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/[USERNAME]/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:1:1)
    at file:///C:/Users/[USERNAME]/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:8:3
    at Object.<anonymous> (file:///C:/Users/[USERNAME]/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:8:3)
    at Object.<anonymous> (file:///C:/Users/[USERNAME]/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:1:1)
    at Module._compile (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/[USERNAME]/.atom/packages/placeholder-text/lib/placeholder-text.coffee:1:23)
    at Object.<anonymous> (file:///C:/Users/[USERNAME]/.atom/packages/placeholder-text/lib/placeholder-text.coffee:1:1)
    at Module._compile (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:715:27)
    at C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\[USERNAME]\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-in-browser"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-jquery-mobile, v0.2.2
branch-status, v0.8.3
color-picker, v2.1.1
data-atom, v0.20.0
docblockr, v0.7.3
github-issues, v0.7.0
goto-definition, v1.1.16
javascript-snippets, v1.2.1
jQuery, v1.2.4
jquery-snippets, v11.0.0
language-sql-mysql, v0.3.1
linter, v1.11.4
linter-csslint, v1.3.2
linter-jshint, v2.1.0
minimap, v4.24.2
open-in-browsers, v0.0.13
php-debug, v0.2.2
pigments, v0.26.3
placeholder-text, v0.1.1
remote-edit, v1.8.24
Remote-FTP, v0.7.20
remote-sync, v4.0.1
smart-daemon-control, v0.8.6
sync-settings, v0.7.2
tree-view-git-branch, v0.1.2

# Dev
No dev packages
```

Too bad, I really need this.

**Comment by nicorikken** [comment]
I have taken a look at the stacktrace and spent a couple of minutes too look into this issue. The `SelectListView` has been deprecated, although it can be activated using the [atom-space-pen-views](https://www.npmjs.com/package/atom-space-pen-views) package. Likewise the workspace commands have changed https://discuss.atom.io/t/replacement-for-atom-workspaceview-command/13636/3 So this package is in need of updating. With my current Javascript skills this would take a while, and so I opt for using a different package altogether. Maybe @Nonameghost or any of you are willing to pick this up.
