### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by wormeyman** [Nonameghost/atom-placeholder-text#8]
[Enter steps to reproduce below:]
1. Try to install from atom
2. It says post this here.

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [placeholder-text](https://github.com/NoNameGhost/atom-placeholder-text) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:4:199)
  at C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:8:3
  at Object.<anonymous> (C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:62:5)
  at Object.<anonymous> (C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text.coffee:1:23)
  at Object.<anonymous> (C:\Users\ejohnson\.atom\packages\placeholder-text\lib\placeholder-text.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:709:34)
  at Package.module.exports.Package.activateConfig (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:201:12)
  at C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:235:24
  at C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\emissary\lib\emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\emissary\lib\emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\emissary\lib\emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:546:19)
  at C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:369:26
  at exit (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\ejohnson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -3:45.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:37 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:58.8.0 core:backspace (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.7
editorconfig, v1.0.1
file-icons, v1.5.8
fonts, v0.5.0
highlight-selected, v0.10.1
language-vbscript, v0.6.1
minimap, v4.10.1
pigments, v0.8.2

# Dev
No dev packages
```

**Comment by rugk** [comment]
:+1: Also have this error.

**Comment by chrisdubya** [comment]
This issue is also happening when opening Atom.
