### ISSUE TITLE
Failed to activate the placeholder-text package

### ISSUE THREAD

**Issue by miukimiu** [Nonameghost/atom-placeholder-text#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10
**Thrown From**: [placeholder-text](https://github.com/NoNameGhost/atom-placeholder-text) package, v0.1.1

### Stack Trace

Failed to activate the placeholder-text package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/miukimiu/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:1:1)
  at /Users/miukimiu/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:8:3
  at Object.<anonymous> (/Users/miukimiu/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:62:5)
  at Object.<anonymous> (/Users/miukimiu/.atom/packages/placeholder-text/lib/placeholder-text-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/miukimiu/.atom/packages/placeholder-text/lib/placeholder-text.coffee:1:23)
  at Object.<anonymous> (/Users/miukimiu/.atom/packages/placeholder-text/lib/placeholder-text.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -9:31.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -8:32 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:30.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:59.2.0 placeholder-text:toggle (atom-text-editor.editor.is-focused)
     -5:33.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  2x -5:19.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -3:25.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -3:23.5.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -3:22.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:21.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:05.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.5.0 placeholder-text:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
placeholder-text, v0.1.1

# Dev
No dev packages
```

**Comment by aaromnido** [comment]
I just find the same issue. :(
Any solution?
